    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20 version
      ansible.builtin.command: dnf module enable nodejs:20 -y
    
    - name: install nodejs package 
      ansible.builtin.package:
        name: "{{ item }}"
        state: "present"
      loop:
      - nodejs
      - mysql

    - name: create an expense user
      ansible.builtin.user:
        name: "expense"

    - name: include from common roles
      include_role:
        name: common
        tasks_from: main 
#    - name: create an /app directory
#      ansible.builtin.file:
#        path: /app
#        state: directory
    
#    - name: Download the backend file 
#      ansible.builtin.get_url:
#        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#        dest: /tmp/backend.zip
    
#    - name: unzip the backend file
#      ansible.builtin.unarchive:
#        src: /tmp/backend.zip
#        dest: /app
#        remote_src: yes

    - name: install depedencies
      community.general.npm:
        path: /app
    
    - name: transfer backend service file
      ansible.builtin.template:
        src: backend.service.j2
        dest: /etc/systemd/system/backend.service

    - name: install python libs
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: "pip3"
      loop:
      - cryptography
      - PyMySQL 

    - name: import SQL data
      community.mysql.mysql_db:
        state: import
        name: all
        login_user: "{{ MYSQL_USER }}"
        login_password: "{{ MYSQL_PASSWORD }}"
        login_host: "{{ MYSQL_HOST }}"
        target: /app/schema/backend.sql

    - name: Restart backend services
      tags:
      - deployment
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: true
        daemon_reload: true