- name: hello playbook
  hosts: mysql
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: "Hello world"
    - name: print Hello Sunil
      ansible.builtin.debug:
        msg: "Hello Sunil"