- name: hello playbook
  hosts: mysql
  tasks:
    - name: print hello world
      ansible.builtin.debug
      msg: "Hello world"

    - name: print hello ivc
      ansible.builtin.debug
      msg: "Hello sunil"