- name: Variables
  hosts: local
  connection: local
  vars:
    COURSE: "AWS with Devops"
    TRAINER: "Sunilkumarivc"
    DURATION: "120 hours"
  tasks: #Print the Variables
  - name: Print the Variables
    ansible.builtin.debug:
    msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
