- name: Print Variables from Files
  hosts: local
  connection: local
  vars:
  - course.yaml
  tasks:
  - name: Task to print variables from Files
    ansible.builtin.debug:
      debug: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
