- name: Devops with course information
  hosts: local
  connection: local
  vars:
    course_name: "Devops with AWS"
    DURATION: "120 hours"
    TOPICS:
    - "Ansible"
    - "Terraform"
    - "shell"
    LIVE: true
    tools:
      ci: jenkins
      cloud: AWS
      containerization: docker
  tasks:
  - name: "Print data types information"
    ansible.builtin.debug:
      msg: 
      - "Course is {{course_name}}"
      - "Duration is {{DURATION}}"
      - "Topics are {{TOPICS}}"
      - " is  it live? {{LIVE}}"
      - "Tools are {{tools}}"

