  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
      - nginx
    
    - name: enable nginx service 
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true
    
#    - name: Remove the default files in nginx
#      ansible.builtin.file:
#        path: /usr/share/nginx/html
#        state: absent 
    
#    - name: Create html directory
#      ansible.builtin.file:
#        path: /usr/share/nginx/html
#        state: directory
        
#    - name: Download the frontend files
#      ansible.builtin.get_url:
#        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#        dest: /tmp/frontend.zip
    
#    - name: unzip the frontend files
#      ansible.builtin.unarchive:
#        src: /tmp/frontend.zip
#        dest: /usr/share/nginx/html
#        remote_src: yes 
    
    - name: transfer expense configuration
      ansible.builtin.template:
        src: backend.service.j2 
        dest: /etc/nginx/default.d/expense.conf
      notify:
      - restart the nginx service

